dist: trusty
sudo: required

language: c
compiler:
  - gcc
  - clang

env:
  global:
    - PREFIX="$TRAVIS_BUILD_DIR/build/install"

script:
  - mkdir -p "$PREFIX"
  - mkdir -p build && cd build && cmake "-DCMAKE_INSTALL_PREFIX=$PREFIX" ..
  - make && make install
